### ISSUE TITLE
get_measurement_for_host host in Host raises error

### ISSUE THREAD

**Issue by mgmonteleone** [mgmonteleone/python-atlasapi#90]
calling 

```python
    a_host.store_measurement(measurements_datasize, AtlasMeasurementTypes.Db.data_size)
```

```python
Traceback (most recent call last):
  File "/Users/mgm/Code/tablesReport/atlas.py", line 167, in <module>
    a_host.store_measurement(measurements_datasize, AtlasMeasurementTypes.Db.data_size)
  File "/Users/mgm/Code/tablesReport/atlas.py", line 66, in store_measurement
    for each_measurement in list(measurements_obj)[0].measurements:
  File "/Users/mgm/Code/tablesReport/venv/lib/python3.9/site-packages/atlasapi/specs.py", line 540, in get_measurement_for_host
    group_id=self.atlas.group,
AttributeError: 'Host' object has no attribute 'atlas'
```

**Comment by mgmonteleone** [comment]
Need to change this to pass an Atlas object.
